version: "3"

networks:
  default:
    external:
      name: external-net

services:
  influxdb:
    container_name: influxdb
    hostname: influxdb          
    image: quay.io/influxdb/influxdb:v2.0.3
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxDB:/root/.influxdbv2
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    container_name: influxdb_cli
    hostname: influxdb_cli          
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
    entrypoint:
      influx setup --bucket dex -t OGymrpHW2WrG3pMwlGWQ2ZKtYJR5KxGoEFL -o zinnion --username=zinnion --password=Br@sa154 --host=http://influxdb:8086 -f
      # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service.
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    container_name: telegraf
    hostname: telegraf     
    # entrypoint:
    #   telegraf --config /telegraf.conf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/telegraf.conf
    depends_on:
      - influxdb_cli

  # badger_pancakeswap:
  #   image: zinnionlcc/node
  #   hostname: badger_pancakeswap
  #   container_name: badger_pancakeswap
  #   restart: unless-stopped        
  #   environment:
  #     - MINIO_ACCESS_KEY=admin
  #     - MINIO_SECRET_KEY=Br@sa154
  #     - PKG=badger
  #     - DEX=pancakeswap
  #     - CHAIN=bsc
  #   depends_on:
  #      - influxdb
  #   command:
  #     - start.sh
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "2m"
  #       max-file: "10"