version: "3"

networks:
  default:
    external:
      name: external-example

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

volumes:
  redis: {}        
